spring:
  ## Redis??
  redis:
    host: 192.168.1.11
    port: 6379
    jedis:
      pool:
        #?????
        max-active: 8
        #????????(???????)
        max-wait: -1
        #????
        min-idle: 0
        #????
        max-idle: 8
    #??????
    timeout: 10000
    ##Redisson??



